Micro Reddit
OlawaleJoseph/micro-reddit pull request #1
Opened 2020-08-06 14:29 UTC by OlawaleJoseph

This a project based on understanding the concepts of ActiveRecord in Ruby on Rails.

### Testing
- Get a local copy of this repo
  Open a terminal and run: ```git clone git@github.com:OlawaleJoseph/micro-reddit.git```
- Open a terminal and run ```bunle install```
- Run ```yarn install --check-files```
- Run ```rails c ```
- Create the following Entities to test
  - User (name: string)
  - Post (body: string)
  - Comment (body: string)

2020-08-06 22:54 UTC, uryelah requested changes
Hi **Wale Adedeko & Mark Kiptubei**, I'm Sarah your reviewer for this PR 👩‍🚀 

Great job with the relations and validations! Everything but one thing seems to be fine!
Check the comments below for the required changes and keep on excelling! 

# Required Changes 🏗️ 🐛 💡

- [ ] Your post is missing a title column, make sure to add the necessary migration and validation.

- [ ] Make sure to capitalize your commit for [best practices](https://chris.beams.io/posts/git-commit/).

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-08-06 22:54 UTC, uryelah commented on app/models/post.rb
> +  validates :user_id, presence: true
- [ ] The belongs_to relation already validates the user_id for you, so this line is unnecessary.

- [ ] You are missing the title validation, the post should have both a body and a title.

2020-08-07 07:53 UTC, mosesogwo requested changes
**Hello! Great job on this :+1:. Just a few changes and you can :rocket:**

:point_right: Add validations to prevent creating a comment with an invalid body, say empty strings.

:point_right: See comment on your README

_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-08-07 07:53 UTC, mosesogwo commented on README.md
> +> This is a project done with the aim of understanding how ActiveRecord works in rails.
You could add a description of the models and associations present in the project.

2020-08-07 10:40 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

2020-08-07 10:56 UTC, merged